import {requireAdmin} from '../_lib/access.js';
import {dbPing,databaseConfigured} from '../_lib/db.js';
import {storageBackend,persistentStoreConfigured} from '../_lib/store.js';
import {allAccounts} from '../_lib/accounts.js';
import {billingConfig} from '../_lib/billing.js';
import {emailConfig} from '../_lib/email.js';
export default async function handler(req,res){
 try{await requireAdmin(req);if(req.method!=='GET')return res.status(405).json({error:'GET only'});const db=databaseConfigured()?await dbPing():{configured:false,ok:false,latencyMs:null};const users=await allAccounts(),billing=billingConfig(),email=emailConfig();const checks={sessionSecret:Boolean(process.env.SESSION_SECRET&&process.env.SESSION_SECRET.length>=24),database:databaseConfigured(),persistentStore:persistentStoreConfigured(),cronSecret:Boolean(process.env.CRON_SECRET),marketData:Boolean(process.env.ALPHAVANTAGE_API_KEY),ibkr:Boolean(process.env.IBKR_BASE_URL&&process.env.IBKR_ACCOUNT_ID),backupSecret:Boolean(process.env.BACKUP_EXPORT_SECRET),email:email.configured,billingTest:billing.enabled};const warnings=[];if(!checks.database)warnings.push('DATABASE_URL not configured; production should use PostgreSQL.');if(!checks.backupSecret)warnings.push('BACKUP_EXPORT_SECRET not configured; full credential backup disabled.');if(!checks.cronSecret)warnings.push('CRON_SECRET not configured.');if(!checks.email)warnings.push('Transactional email is not configured.');if(billing.mode!=='disabled'&&!billing.enabled)warnings.push('Billing safety check failed: v1.3 accepts only Stripe test mode with sk_test_ key.');return res.status(200).json({version:'1.3',paperOnly:true,storageBackend:storageBackend(),database:db,checks,warnings,users:{total:users.length,active:users.filter(x=>x.status==='active').length},email:{mode:email.mode,configured:email.configured},billing:{enabled:billing.enabled,mode:billing.mode,testMode:billing.testMode,webhookConfigured:billing.webhookConfigured},liveExecution:false})}catch(e){return res.status(e.status||500).json({error:e.message})}
}
