import {getJson,setJson} from './store.js';
import {entitlements} from './plans.js';
import {databaseConfigured,db} from './db.js';
function monthKey(d=new Date()){return d.toISOString().slice(0,7)}
function key(user,month=monthKey()){return `tcc:${user}:usage:${month}`}
export async function getUsage(user,month=monthKey()){
 if(databaseConfigured()){const sql=await db();const rows=await sql`select feature,count,updated_at from tcc_usage where username=${user} and month=${month}`;const counters={};let updatedAt=null;for(const r of rows){counters[r.feature]=Number(r.count||0);const ts=r.updated_at?new Date(r.updated_at).toISOString():null;if(ts&&(!updatedAt||ts>updatedAt))updatedAt=ts}return {month,counters,updatedAt}}
 return (await getJson(key(user,month)))||{month,counters:{},updatedAt:null}
}
export async function incrementUsage(user,feature,amount=1){const month=monthKey(),inc=Math.max(0,Number(amount||0));if(databaseConfigured()){const sql=await db();const rows=await sql`insert into tcc_usage (username,month,feature,count,updated_at) values (${user},${month},${feature},${inc},now()) on conflict (username,month,feature) do update set count=tcc_usage.count+${inc},updated_at=now() returning count,updated_at`;const u=await getUsage(user,month);return u}const u=await getUsage(user,month);u.counters={...(u.counters||{})};u.counters[feature]=Math.max(0,Number(u.counters[feature]||0)+inc);u.updatedAt=new Date().toISOString();await setJson(key(user,month),u);return u}
export async function consumeUsage(account,feature,amount=1,{enforce=true}={}){const e=entitlements(account.plan),map={marketSymbols:'monthlyMarketSymbols',manualScans:'monthlyManualScans',paperOrders:'monthlyPaperOrders'},limit=Number(e[map[feature]]||0),inc=Math.max(0,Number(amount||0)),month=monthKey();if(databaseConfigured()&&enforce&&limit>0){if(inc>limit){const err=new Error(`${e.label} monthly ${feature} limit reached (0/${limit})`);err.status=429;err.code='USAGE_LIMIT';throw err}const sql=await db();const rows=await sql`insert into tcc_usage (username,month,feature,count,updated_at) values (${account.username},${month},${feature},${inc},now()) on conflict (username,month,feature) do update set count=tcc_usage.count+${inc},updated_at=now() where tcc_usage.count+${inc}<=${limit} returning count`;if(!rows.length){const cur=await sql`select count from tcc_usage where username=${account.username} and month=${month} and feature=${feature}`;const current=Number(cur[0]?.count||0);const err=new Error(`${e.label} monthly ${feature} limit reached (${current}/${limit})`);err.status=429;err.code='USAGE_LIMIT';err.usage={feature,current,limit,month};throw err}return getUsage(account.username,month)}const u=await getUsage(account.username,month),current=Number(u.counters?.[feature]||0),next=current+inc;if(enforce&&limit>0&&next>limit){const err=new Error(`${e.label} monthly ${feature} limit reached (${current}/${limit})`);err.status=429;err.code='USAGE_LIMIT';err.usage={feature,current,limit,month:u.month};throw err}return incrementUsage(account.username,feature,inc)}
export function usageSummary(u,plan){const e=plan?entitlements(plan):null;return {month:u?.month||monthKey(),counters:u?.counters||{},limits:e?{marketSymbols:e.monthlyMarketSymbols,manualScans:e.monthlyManualScans,paperOrders:e.monthlyPaperOrders}:null,updatedAt:u?.updatedAt||null}}
