import assert from 'node:assert/strict';
import {createBot,tickBot,evaluateSignal,botMetrics} from '../server/api/_lib/paper-bot.js';
import {mutateBot,readBot} from '../server/api/_lib/bot-store.js';
import {fetchBotSnapshot} from '../server/api/_lib/bot-feed.js';
const now=Date.parse('2026-09-26T10:00:00Z');
const candles=Array.from({length:60},(_,i)=>({ts:now-(60-i)*60000,close:100+i*.1}));
const snap={quote:{symbol:'BTC-EUR',bid:106,ask:106.1,ts:now},candles,news:{status:'OK',fetchedAt:now,articles:[],negative:false}};
let s={...createBot({},now),enabled:true};
assert.equal(evaluateSignal(candles,snap.news,now).accepted,true);
s=tickBot(s,snap,now);assert.ok(s.position);assert.ok(Math.abs(s.position.stop/s.position.entry-.95)<1e-10);
assert.deepEqual(tickBot(s,snap,now),s);
const lossSnap={...snap,quote:{...snap.quote,bid:99,ask:99.1,ts:now+1000}};
const closed=tickBot(s,lossSnap,now+1000);assert.equal(closed.trades.length,1);assert.equal(closed.trades[0].reason,'STOP');assert.ok(closed.trades[0].pnl<0);
assert.ok(Math.abs(closed.cash-(100+closed.trades[0].pnl))<1e-8);
assert.throws(()=>tickBot(s,snap,now+100000),/STALE/);
assert.throws(()=>tickBot(s,{...snap,quote:{...snap.quote,bid:NaN}},now),/INVALID/);
assert.equal(tickBot({...createBot({},now),enabled:true},{...snap,news:{status:'UNAVAILABLE'}},now).position,null);
assert.equal(tickBot({...createBot({},now),enabled:true},snap,now,{allowEntry:false}).position,null);
assert.equal(tickBot({...createBot({},now),enabled:true},{...snap,news:{...snap.news,negative:true}},now).position,null);
assert.equal(tickBot({...createBot({},now),cash:89,enabled:true},snap,now).monthHalt,'MONTHLY_LOSS_LIMIT');
assert.equal(tickBot({...createBot({},now),cash:301,enabled:true},snap,now).monthHalt,'MONTHLY_PROFIT_CAP');
assert.equal(tickBot({...s,enabled:false},lossSnap,now+1000,{allowEntry:false}).trades.length,1);
const target=tickBot(s,{...snap,quote:{...snap.quote,bid:120,ask:120.1,ts:now+1000}},now+1000);assert.equal(target.trades[0].reason,'TARGET');
assert.equal(botMetrics(createBot({},now)).winRate,null);
assert.throws(()=>createBot({plan:'a',capital:101}),/Invalid/);
assert.throws(()=>createBot({capital:NaN}),/Invalid/);
const gap=structuredClone(candles);gap[3].ts-=60000;assert.equal(evaluateSignal(gap,snap.news,now).accepted,false);
process.env.BOT_LOCAL_DEMO='true';
await mutateBot('test',()=>({...createBot({},now),enabled:true}));
await Promise.all(Array.from({length:12},()=>mutateBot('test',x=>tickBot(x,snap,now))));
assert.equal((await readBot('test')).events.filter(e=>e.type==='OPEN').length,1);
const before=await readBot('test');await assert.rejects(mutateBot('test',()=>{throw Error('rollback')}));assert.deepEqual(await readBot('test'),before);
const mock=async url=>({ok:true,json:async()=>url.includes('ticker')?{code:'0',data:[{instId:'BTC-EUR',bidPx:'106',askPx:'106.1',ts:String(now)}]}:url.includes('candles')?{code:'0',data:candles.slice().reverse().map(c=>[String(c.ts),'','','',String(c.close),'','','','1'])}:{articles:[]}});
const fetched=await fetchBotSnapshot({fetcher:mock,now});assert.deepEqual(fetched.quote,snap.quote);assert.equal(fetched.candles.length,60);
const nextMonth=Date.parse('2026-10-01T01:00:00Z');
const monthly=tickBot({...createBot({},now),cash:89,monthHalt:'MONTHLY_LOSS_LIMIT'}, {...snap,quote:{...snap.quote,ts:nextMonth}},nextMonth);
assert.equal(monthly.monthHalt,null);assert.equal(monthly.monthStartEquity,89);
assert.equal(tickBot({...createBot({},now),cash:110,monthHalt:'MONTHLY_LOSS_LIMIT',enabled:true},snap,now).position,null);
process.env.NODE_ENV='production';await assert.rejects(mutateBot('prod-test',()=>createBot({},now)),/DATABASE_REQUIRED/);delete process.env.NODE_ENV;
console.log('bot-smoke: PASS — entries, exits, fees, freshness, news gates, monthly limits, replay and concurrent requests');
